name: Generate GitArtWork

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Make GitArtWork SVG
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: jasineri/gitartwork@v1
        with:
          # Your GitHub username
          user_name: MehakHarlapur

          # The text you want to appear
          text: MEHAK DEV

      - uses: jasineri/simple-push-action@v1